Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false
  
Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false
  